<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | INCO CMS</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-[#f5f8fc] text-slate-700 antialiased">
    <div class="admin-shell">
        <aside class="admin-sidebar w-full border-b border-slate-200 bg-white lg:border-b-0 lg:border-r">
            <div class="flex h-16 items-center gap-2 border-b border-slate-200 px-4">
                <div class="flex h-8 w-8 items-center justify-center rounded-md bg-sky-500 text-sm font-black text-white">I</div>
                <div class="leading-tight"><p class="text-sm font-extrabold text-slate-900">INCO CMS</p><p class="text-[9px] text-slate-400">Event management</p></div>
            </div>
            <nav class="flex gap-1 overflow-x-auto p-3 lg:block lg:space-y-1">
                <p class="hidden px-3 pb-2 pt-2 text-[9px] font-bold uppercase tracking-widest text-slate-400 lg:block">Main menu</p>
                @foreach ([['Dashboard', '/dashboard', 'bi-grid', true], ['Kategori', route('admin.categories.index'), 'bi-tags', false], ['Event', route('admin.events.index'), 'bi-calendar-event', false], ['Galeri', '#', 'bi-images', false], ['Artikel', '#', 'bi-file-earmark-text', false], ['Partner', '#', 'bi-people', false], ['Pesan Kontak', '#', 'bi-envelope', false]] as [$label, $url, $icon, $active])
                    <a href="{{ $url }}" class="flex min-w-max items-center gap-3 rounded-md px-3 py-2.5 text-xs font-semibold {{ $active ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900' }}"><i class="bi {{ $icon }} w-4 text-center text-sm {{ $active ? 'text-blue-500' : 'text-slate-400' }}"></i>{{ $label }}</a>
                @endforeach
            </nav>
            <div class="hidden border-t border-slate-200 p-3 lg:absolute lg:inset-x-0 lg:bottom-0 lg:block">
                <div class="flex items-center gap-2 rounded-md border border-blue-100 bg-blue-50/60 p-2.5"><div class="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-100 text-[10px] font-bold text-emerald-700">{{ strtoupper(substr(auth()->user()->name, 0, 2)) }}</div><div class="min-w-0"><p class="truncate text-xs font-bold text-slate-800">{{ auth()->user()->name }}</p><p class="text-[10px] text-slate-400">Active Workspace</p></div></div>
                <form method="POST" action="{{ route('logout') }}" class="mt-2">@csrf<button class="w-full rounded-md px-2.5 py-2 text-left text-xs font-semibold text-slate-500 hover:bg-red-50 hover:text-red-600">↪ &nbsp; Logout</button></form>
            </div>
        </aside>

        <main class="admin-main">
            <header class="flex min-h-12 items-center justify-between gap-4 border-b border-slate-200 bg-white px-4 sm:px-6">
                <div class="flex min-w-0 flex-1 items-center gap-3"><button class="hidden h-7 w-7 rounded border border-slate-200 text-slate-500 sm:block" title="Toggle menu">☰</button><div class="relative w-full max-w-md"><span class="absolute left-3 top-1.5 text-sm text-slate-400">⌕</span><input type="search" placeholder="Search events, partners, reports" class="h-7 w-full rounded border border-slate-200 bg-white pl-8 pr-3 text-[11px] outline-none placeholder:text-slate-400 focus:border-blue-400"></div></div>
                <div class="flex items-center gap-2"><button class="hidden h-7 w-7 rounded border border-slate-200 text-xs text-slate-500 sm:block" title="Toggle theme">◔</button><button class="relative h-7 w-7 rounded border border-slate-200 text-xs text-slate-500" title="Notifications">♧<span class="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-red-500"></span></button><div class="flex items-center gap-2 border-l border-slate-200 pl-3"><div class="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-100 text-[9px] font-bold text-emerald-700">{{ strtoupper(substr(auth()->user()->name, 0, 2)) }}</div><span class="hidden text-[11px] font-semibold text-slate-700 sm:block">{{ auth()->user()->name }}</span><span class="text-[10px] text-slate-400">⌄</span></div></div>
            </header>

            <div class="p-4 sm:p-6">
                <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-[9px] font-bold uppercase tracking-widest text-blue-600">Overview</p><h1 class="text-2xl font-extrabold tracking-tight text-slate-900">Welcome back, Admin!</h1><p class="mt-1 text-[11px] text-slate-500">Manage R27 Creative Agency events and digital content from one place.</p></div><div class="flex gap-2"><button class="rounded border border-slate-200 bg-white px-3 py-2 text-[11px] font-semibold text-slate-600 shadow-sm hover:border-blue-300 hover:text-blue-600"><i class="bi bi-download me-1"></i> Export</button><a href="{{ route('admin.events.create') }}" class="rounded bg-blue-600 px-3 py-2 text-[11px] font-semibold text-white shadow-sm hover:bg-blue-700"><i class="bi bi-plus-lg me-1"></i> Add Event</a></div></div>

                <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                    @foreach ([['TOTAL EVENTS', $metrics['events'], 'Event terdaftar', 'border-blue-500', 'bg-blue-50', 'text-blue-600'], ['ACTIVE EVENTS', $metrics['activeEvents'], 'Upcoming & ongoing', 'border-emerald-500', 'bg-emerald-50', 'text-emerald-600'], ['SERVICES', $metrics['articles'], 'Content modules', 'border-amber-500', 'bg-amber-50', 'text-amber-600'], ['PARTNERS', $metrics['partners'], 'Partner terdaftar', 'border-red-500', 'bg-red-50', 'text-red-500']] as [$label, $value, $caption, $border, $badge, $color])
                        <div class="border border-slate-200 border-l-2 {{ $border }} bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><p class="text-[9px] font-bold tracking-wide text-slate-500">{{ $label }}</p><span class="rounded {{ $badge }} px-2 py-1 text-[10px] font-bold {{ $color }}">↗</span></div><p class="mt-3 text-2xl font-extrabold text-slate-900">{{ number_format($value) }}</p><p class="mt-1 text-[10px] text-slate-400">{{ $caption }}</p></div>
                    @endforeach
                </section>

                <section class="mt-3 grid gap-3 xl:grid-cols-[1.7fr_0.9fr]">
                    <div class="border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><div class="flex items-center gap-2"><span class="flex h-6 w-6 items-center justify-center rounded bg-blue-50 text-xs text-blue-600">⌁</span><h2 class="text-sm font-bold text-slate-800">Event Performance</h2></div><p class="mt-1 text-[10px] text-slate-400">Jumlah event per bulan pada {{ now()->year }}</p></div><button class="rounded border border-slate-200 px-2 py-1 text-[10px] font-semibold text-slate-600">View Details</button></div><div class="mt-6 flex h-36 items-end gap-2 border-b border-slate-100 px-1 sm:h-40 sm:gap-3">@foreach ($monthlyTotals as $total)<div class="flex h-full flex-1 flex-col justify-end"><div class="rounded-t bg-gradient-to-t from-teal-600 to-blue-600 transition hover:from-teal-500 hover:to-blue-500" style="height: {{ $total ? max(10, min(100, $total * 14)) : 4 }}%" title="{{ $total }} event"></div><span class="mt-2 text-center text-[9px] text-slate-400">{{ $monthlyLabels[$loop->index] }}</span></div>@endforeach</div></div>
                    <div class="border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between"><div><div class="flex items-center gap-2"><span class="flex h-6 w-6 items-center justify-center rounded bg-blue-50 text-xs text-blue-600">⌁</span><h2 class="text-sm font-bold text-slate-800">Team Activity</h2></div><p class="mt-1 text-[10px] text-slate-400">Recent operational updates</p></div><button class="text-sm text-slate-400">•••</button></div><div class="mt-4 divide-y divide-slate-100">@forelse ($recentActivities as $activity)<div class="flex gap-2.5 py-3 first:pt-0"><span class="mt-1 h-2 w-2 shrink-0 rounded-full {{ $loop->index === 1 ? 'bg-emerald-500' : ($loop->index === 2 ? 'bg-amber-400' : 'bg-blue-500') }}"></span><div><p class="text-[11px] font-semibold text-slate-700">{{ $activity->name }}</p><p class="mt-1 text-[9px] text-slate-400">{{ ucfirst($activity->status) }} · {{ $activity->created_at->diffForHumans() }}</p></div></div>@empty<p class="py-4 text-[11px] text-slate-400">Belum ada aktivitas.</p>@endforelse</div></div>
                </section>

                <section id="events" class="mt-3 border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><div class="flex items-center gap-2"><span class="flex h-6 w-6 items-center justify-center rounded bg-blue-50 text-xs text-blue-600">♙</span><h2 class="text-sm font-bold text-slate-800">Recent Events</h2></div><p class="mt-1 text-[10px] text-slate-400">Event terbaru dalam workspace</p></div><button class="rounded border border-slate-200 px-2 py-1 text-[10px] font-semibold text-slate-600">Manage Events</button></div><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left"><thead class="bg-slate-50 text-[9px] uppercase tracking-wider text-slate-400"><tr><th class="px-4 py-3 font-bold">Event</th><th class="px-4 py-3 font-bold">Kategori</th><th class="px-4 py-3 font-bold">Tanggal</th><th class="px-4 py-3 font-bold">Status</th><th class="px-4 py-3 text-right font-bold">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($recentEvents as $event)<tr class="hover:bg-blue-50/30"><td class="px-4 py-3"><p class="text-[11px] font-semibold text-slate-800">{{ $event->name }}</p><p class="mt-0.5 text-[9px] text-slate-400">{{ \Illuminate\Support\Str::limit($event->description, 45) }}</p></td><td class="px-4 py-3 text-[10px] text-slate-500">{{ $event->category?->name ?? 'Tanpa kategori' }}</td><td class="px-4 py-3 text-[10px] text-slate-500">{{ $event->start_date?->format('d M Y') ?? '-' }}</td><td class="px-4 py-3"><span class="rounded px-2 py-1 text-[9px] font-bold {{ $event->status === 'approved' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ ucfirst($event->status) }}</span></td><td class="px-4 py-3 text-right"><button class="rounded border border-slate-200 px-2 py-1 text-[9px] font-semibold text-slate-600 hover:border-blue-300 hover:text-blue-600">View</button></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-[11px] text-slate-400">Belum ada event.</td></tr>@endforelse</tbody></table></div></section>
                <section class="mt-3 grid gap-3 lg:grid-cols-2"><div class="border border-slate-200 bg-white p-4 shadow-sm"><div class="mb-3 flex items-center justify-between"><div><h2 class="text-sm font-bold text-slate-800">Artikel Terbaru</h2><p class="mt-1 text-[10px] text-slate-400">Konten terbaru yang masuk</p></div><span class="rounded bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-600">{{ $metrics['articles'] }} total</span></div>@forelse ($recentArticles as $article)<div class="flex items-center justify-between border-t border-slate-100 py-2.5"><p class="text-[11px] font-semibold text-slate-700">{{ $article->title ?? $article->name ?? 'Artikel tanpa judul' }}</p><span class="text-[9px] text-slate-400">{{ optional($article->created_at)->diffForHumans() }}</span></div>@empty<p class="border-t border-slate-100 pt-3 text-[11px] text-slate-400">Modul artikel belum memiliki data.</p>@endforelse</div><div class="border border-slate-200 bg-white p-4 shadow-sm"><div class="mb-3"><h2 class="text-sm font-bold text-slate-800">Event per Kategori</h2><p class="mt-1 text-[10px] text-slate-400">Distribusi event saat ini</p></div>@forelse ($categoryEventCounts as $category)<div class="flex items-center justify-between border-t border-slate-100 py-2.5"><span class="text-[11px] font-semibold text-slate-700">{{ $category->name }}</span><span class="rounded-full bg-blue-50 px-2.5 py-1 text-[9px] font-bold text-blue-600">{{ $category->events_count }} event</span></div>@empty<p class="border-t border-slate-100 pt-3 text-[11px] text-slate-400">Belum ada kategori event.</p>@endforelse</div></section>
            </div>
        </main>
    </div>
</body>
</html>