@extends('layouts.admin')
@section('title', 'Teams')
@section('content')
<div class="min-h-[calc(100vh-4rem)] bg-white px-4 py-8 sm:px-8 lg:px-10"><div class="mx-auto max-w-[1400px]">
    <header class="mb-8 flex items-center justify-between gap-4"><div><h1 class="text-3xl font-bold tracking-tight text-[#16324f]">Teams</h1><p class="mt-1 text-base text-slate-400">{{ $teams->total() }} anggota team</p></div><a href="{{ route('admin.teams.create') }}" class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-slate-200 bg-white text-2xl font-light leading-none text-slate-700 shadow-[0_8px_18px_rgba(15,23,42,0.08)] transition duration-200 hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-[0_12px_22px_rgba(15,23,42,0.12)]" style="line-height: 1;" title="Tambah Team" aria-label="Tambah Team">+</a></header>
    <section class="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3">
        @forelse ($teams as $team)
            <article class="rounded-2xl border border-[#dceaf7] bg-white p-6 text-center shadow-sm"><div class="mx-auto flex h-28 w-28 items-center justify-center overflow-hidden rounded-full bg-[#eff7ff] text-4xl text-sky-400">@if ($team->photo)<img src="{{ asset('storage/' . $team->photo) }}" alt="{{ $team->name }}" class="h-full w-full object-cover">@else<i class="bi bi-person-fill"></i>@endif</div><h2 class="mt-5 text-lg font-bold text-[#16324f]">{{ $team->name }}</h2><p class="mt-1 text-sm text-sky-500">{{ $team->position }}</p><p class="mt-3 min-h-10 text-sm leading-5 text-slate-400">{{ $team->bio }}</p><div class="mt-5 flex items-center justify-center gap-3"><a href="{{ route('admin.teams.edit', $team) }}" title="Edit team member" class="flex h-9 w-9 items-center justify-center rounded-full border border-slate-200 bg-white text-lg font-light leading-none text-slate-700 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-[0_8px_14px_rgba(15,23,42,0.08)]" style="line-height: 1;">+</a><form method="POST" action="{{ route('admin.teams.destroy', $team) }}" onsubmit="return confirm('Hapus anggota team ini?')">@csrf @method('DELETE')<button title="Delete team member" class="flex h-9 w-9 items-center justify-center rounded-xl bg-rose-50 text-rose-500"><i class="bi bi-trash3"></i></button></form></div><form method="POST" action="{{ route('admin.teams.toggle-status', $team) }}" class="mt-3">@csrf @method('PATCH')<button class="text-xs font-semibold {{ $team->status === 'published' ? 'text-emerald-500' : 'text-sky-600' }}">{{ $team->status === 'published' ? 'Published' : 'Publish' }}</button></form></article>
        @empty
            <div class="rounded-2xl border border-slate-200 bg-white p-10 xl:col-span-3"><x-admin.empty-state icon="bi-people" title="No team members yet" description="Tambahkan anggota team pertama Anda." /></div>
        @endforelse
    </section>
    @if ($teams->hasPages()) <div class="mt-6 rounded-2xl border border-slate-200 bg-white px-6 py-4">{{ $teams->links() }}</div> @endif
</div></div>
@endsection