@extends('layouts.admin')
@section('title', 'Events')
@section('content')
<div class="mx-auto max-w-[1400px] p-5 sm:p-8">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-blue-600">Event Management</p><h1 class="text-3xl font-bold tracking-tight text-[#16324f]">Events</h1><p class="mt-2 text-sm text-slate-500">Manage all events organized and managed by R27 Creative Agency.</p></div><a href="{{ route('admin.events.create') }}" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><i class="bi bi-plus-lg me-2"></i>Add Event</a></div>
    @if(session('success'))<x-admin.alert>{{ session('success') }}</x-admin.alert>@endif
    <div class="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" class="flex flex-col gap-3 md:flex-row"><div class="relative flex-1"><i class="bi bi-search absolute left-3 top-3 text-slate-400"></i><input name="search" value="{{ request('search') }}" placeholder="Search events..." class="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-400 focus:bg-white"></div><select name="status" class="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400"><option value="">All status</option>@foreach(['draft','upcoming','ongoing','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="h-10 rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white"><i class="bi bi-funnel me-1"></i>Filter</button></form></div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-6 py-4">No</th><th class="px-6 py-4">Event</th><th class="px-6 py-4">Category</th><th class="px-6 py-4">Date</th><th class="px-6 py-4">Location</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($events as $event)<tr class="hover:bg-blue-50/30"><td class="px-6 py-4 text-sm text-slate-400">{{ $events->firstItem() + $loop->index }}</td><td class="px-6 py-4"><p class="text-sm font-semibold text-slate-800">{{ $event->name }}</p><p class="mt-1 text-xs text-slate-400">{{ \Illuminate\Support\Str::limit($event->description, 50) }}</p></td><td class="px-6 py-4 text-sm text-slate-500">{{ $event->category?->name ?? '-' }}</td><td class="px-6 py-4 text-sm text-slate-500">{{ $event->start_date?->format('d M Y') }}</td><td class="px-6 py-4 text-sm text-slate-500">{{ $event->location }}</td><td class="px-6 py-4"><x-admin.status-badge :status="$event->status" /></td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.events.edit', $event) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-blue-300 hover:text-blue-600"><i class="bi bi-pencil me-1"></i>Edit</a><form method="POST" action="{{ route('admin.events.destroy', $event) }}" onsubmit="return confirm('Hapus event ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-100 px-3 py-2 text-xs font-semibold text-red-600 hover:bg-red-50"><i class="bi bi-trash me-1"></i>Delete</button></form></div></td></tr>@empty<tr><td colspan="7"><x-admin.empty-state icon="bi-calendar-x" title="No events yet" description="Add your first event to get started." /></td></tr>@endforelse</tbody></table></div>@if($events->hasPages())<div class="border-t border-slate-100 px-6 py-4">{{ $events->links() }}</div>@endif</div>
</div>
@endsection
